version: '3'

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    networks:
      - bridge-network
  crawler:
    image: certacon_poc_crawler:latest
    ports:
      - "8081:8081"
    environment:
      - API_URL=http://api:8080
      - SITE_URL=https://www.vriconsulting.com.br/guias/guiasIndex.php?idGuia=22
      - SELENIUM_URL=http://selenium:4444/wd/hub
    depends_on:
      - selenium 
      - api
    networks:
      - bridge-network
    command: sh -c '
      echo "Iniciando automaticamente em 60s" &&
      sleep 60 &&
      python crawler.py'
  api:
    image: certacon_poc_api:latest
    ports:
      - "8080:8080"
    networks:
      - bridge-network

  frontend:
    image: certacon_poc_front:latest
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:8080
    depends_on:
      - api 
    networks:
      - bridge-network
networks:
  bridge-network:
    driver: bridge